server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway: #routes traffic from all services to API-GATEWAY
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallback
            - name: RequestRateLimiter # redis for limit request per user
              args:
                redis-rate-limiter.replenishRate: 1 # 1 request per second
                redis-rate-limiter.burstCapacity: 1 # 1 particular requests per second

okta:
  oauth2:
    issuer: https://dev-86709474.okta.com/oauth2/default
    audience: api://default
    client-id: 0oab5ti3duIPmn2135d7
    client-secret: HYB3EOyYwyxqKb0caflBupXywsgUoZp_KTmFkuc98O55KFcSod7Wrfxaf2_K0CJT
    scopes: openid, profile, email, offline_access, internal
    redirect-uri: /login/oauth2/code/okta
    groups-claim: Admin, Customer